modLoader="javafml"
loaderVersion="[31,)"
license="GNU GPL"
issueTrackerURL="https://gitlab.com/Lycanite/LycanitesMobs/issues"

[[mods]]
modId="lycanitesmobs"
version="${file.jarVersion}"
displayName="Lycanites Mobs"
#updateJSONURL="https://api.lycanitesmobs.com/checkUpdate"
displayURL="https://lycanitesmobs.com"
logoFile="lycanitesmobs.png"
credits="Created by Lycanite (Richard Nicholson)"
authors="Lycanite (Richard Nicholson)"
description='''
This mod adds many new mobs to specific biomes, dimensions and more. These mobs range from peaceful Makas, farmable mammal-like reptiles with massive sails (watch out for the alphas) to horrific Grues that are made of the very shadows themselves! Expect to see angry elementals such as Cinders spawning from large fires or Spriggans from tall grass and crops!
'''

[[dependencies.lycanitesmobs]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.0,)"
    ordering="NONE"
    side="BOTH"